### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'var/log/simbak'

### ISSUE THREAD

**Issue by wimmuskee** [mark-bromell/simbak#9]
Using the program (cli or as lib) from the example leads to a FileNotFoundError.
When creating the var/log/simbak directory relative to the workdir, it works (but not really a solution for me).

For my own use case I don't really need a logfile. Perhaps set it the default to /dev/null, and offer optional override.

**Comment by mark-bromell** [comment]
Yeah I will remove the need for logging into files, it can be set up in people's scripts if they want. I was mistaken in forcing file logging with simbak to begin with.

**Comment by wimmuskee** [comment]
Thx for looking into this :)

Don't know if forcing logging is necessarily a bad idea. But depending on use case, the defaults differ. For a root/system user, the /var/log/simbak is probably ok. For regular users the homedir .symbak folder might be a good one. (not sure what the windows equivalents are though)

**Comment by mark-bromell** [comment]
Fixed in [v0.4.0](https://pypi.org/project/simbak/0.4.0/), file logging is now optional, thanks for submitting this issue :)
